---
- name: "PYTHON: 1.1 | Installs dependencies ..."
  become: true
  apt:
    name: '{{ item }}'
    update_cache: true
    state: latest
  loop:
    - build-essential
    - python3-dev
    - python3-pip
    - python3-venv
    - python3-virtualenv
