---
- name: "BASIC: 1.1 | Install dependencies ..."
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop:
    - bash
    - openssh-server
    - python3-psutil
    - acl
    - unzip
    - htop
    - neofetch
    - tmux
    - vim-nox
